name: Build and Test

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 9.3.0
            - uses: actions/setup-node@master
              with:
                  node-version: 20.x
            - name: pnpm module install
              run: pnpm install --frozen-lockfile
            - name: nuxt generate
              run: pnpm run generate
            - uses: actions/upload-artifact@master
              with:
                  name: build-artifact
                  path: .output/public/

    test-cypress:
        name: Cypress Tests
        runs-on: ubuntu-20.04
        needs:
            - build
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 9.3.0
            - uses: actions/setup-node@master
              with:
                  node-version: 20.x
            - uses: actions/download-artifact@master
              with:
                  name: build-artifact
                  path: .output/public/
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npx serve .output/public
                  browser: chrome